# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sidedishApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sidedishApp

  target 'sidedishAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sidedishAppUITests' do
    # Pods for testing
  end

end
